name: GitHub Self-Updating

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. 
    # High load times include the start of every hour. 
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    # Every 5 minutes.
    # - cron: '*/5 * * * *'
    # At the beginning of every day.
    - cron: "0 0 * * *"

# on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v3
      - name: Modify date and time
        run: |
          sed -i '$!N;$s/.*\n/'"China\/Shanghai $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S.%3N')"'\n/;P;D' README.md
      - name: Push to repository
        run: |
          git config --global user.name "Herman Liu"
          git config --global user.email "contactliuhao@gmail.com"
          now=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S.%3N')
          git add -A
          git commit -m "Auto Push via GitHub Actions workflow at China/Shanghai: $now"
          git push
